table 'Spotify Dataset'
	lineageTag: 022e49ee-06e3-4ebb-8aeb-e863703d8852

	column track_name
		dataType: string
		lineageTag: 7839fe27-e0af-4605-900c-987d7893c4dc
		summarizeBy: none
		sourceColumn: track_name

		annotation SummarizationSetBy = Automatic

	column artist(s)_name
		dataType: string
		lineageTag: ea72f3d1-bcce-48fc-ae24-a244411697f2
		summarizeBy: none
		sourceColumn: artist(s)_name

		annotation SummarizationSetBy = Automatic

	column artist_count
		dataType: int64
		formatString: 0
		lineageTag: 58c62c08-92e3-4913-a6b9-0c59b4664336
		summarizeBy: sum
		sourceColumn: artist_count

		annotation SummarizationSetBy = Automatic

	column released_year
		dataType: int64
		formatString: 0
		lineageTag: b9716d6e-4f04-406e-bac6-1466b8c41ade
		summarizeBy: sum
		sourceColumn: released_year

		annotation SummarizationSetBy = Automatic

	column released_month
		dataType: int64
		formatString: 0
		lineageTag: 55e888dd-4056-4d9f-b257-33be2e8a9ec9
		summarizeBy: sum
		sourceColumn: released_month

		annotation SummarizationSetBy = Automatic

	column released_day
		dataType: int64
		formatString: 0
		lineageTag: 41bd175a-f622-4e00-ae60-c3667755f4bc
		summarizeBy: sum
		sourceColumn: released_day

		annotation SummarizationSetBy = Automatic

	column in_spotify_playlists
		dataType: int64
		formatString: 0
		lineageTag: 16668663-d074-45d9-9c62-4ba8fdf65337
		summarizeBy: sum
		sourceColumn: in_spotify_playlists

		annotation SummarizationSetBy = Automatic

	column in_spotify_charts
		dataType: int64
		formatString: 0
		lineageTag: f604de43-5e8b-44a3-ab91-527ee807c032
		summarizeBy: sum
		sourceColumn: in_spotify_charts

		annotation SummarizationSetBy = Automatic

	column streams
		dataType: int64
		formatString: 0
		lineageTag: 0a5dd758-268c-4285-9e6f-bc2d9af1adaf
		summarizeBy: sum
		sourceColumn: streams

		annotation SummarizationSetBy = Automatic

	column in_apple_playlists
		dataType: int64
		formatString: 0
		lineageTag: 4b6856e6-d8ff-4725-bf1e-724a42759759
		summarizeBy: sum
		sourceColumn: in_apple_playlists

		annotation SummarizationSetBy = Automatic

	column in_apple_charts
		dataType: int64
		formatString: 0
		lineageTag: 6a6f32a1-7fb6-490f-bede-10f930e0c976
		summarizeBy: sum
		sourceColumn: in_apple_charts

		annotation SummarizationSetBy = Automatic

	column in_deezer_playlists
		dataType: int64
		formatString: 0
		lineageTag: 1b175f7c-3d3e-4856-88e3-d363a0a9d5a1
		summarizeBy: sum
		sourceColumn: in_deezer_playlists

		annotation SummarizationSetBy = Automatic

	column in_deezer_charts
		dataType: int64
		formatString: 0
		lineageTag: 30765ea6-ddd6-427b-a21b-38a2f1baa616
		summarizeBy: sum
		sourceColumn: in_deezer_charts

		annotation SummarizationSetBy = Automatic

	column in_shazam_charts
		dataType: int64
		formatString: 0
		lineageTag: 14267937-3508-45f4-b19d-5c2e15df3742
		summarizeBy: sum
		sourceColumn: in_shazam_charts

		annotation SummarizationSetBy = Automatic

	column bpm
		dataType: int64
		formatString: 0
		lineageTag: 5039ed4f-e18e-4ee3-8da4-3a58137426a2
		summarizeBy: sum
		sourceColumn: bpm

		annotation SummarizationSetBy = Automatic

	column key
		dataType: string
		lineageTag: 590524be-9f81-4902-9017-9b0b2dcad2dd
		summarizeBy: none
		sourceColumn: key

		annotation SummarizationSetBy = Automatic

	column mode
		dataType: string
		lineageTag: 78cdcaee-ef01-46fe-ad77-07fbccae5b57
		summarizeBy: none
		sourceColumn: mode

		annotation SummarizationSetBy = Automatic

	column danceability_%
		dataType: int64
		formatString: 0
		lineageTag: ed8f4216-ac7f-4962-9c3a-fa733a44178b
		summarizeBy: sum
		sourceColumn: danceability_%

		annotation SummarizationSetBy = Automatic

	column valence_%
		dataType: int64
		formatString: 0
		lineageTag: bcd7d705-f62e-4ffd-8ea5-8528d83ba4fe
		summarizeBy: sum
		sourceColumn: valence_%

		annotation SummarizationSetBy = Automatic

	column energy_%
		dataType: int64
		formatString: 0.00
		lineageTag: 19fbe305-0b98-4ab2-a6be-6bd83713d80f
		summarizeBy: average
		sourceColumn: energy_%

		annotation SummarizationSetBy = User

	column acousticness_%
		dataType: int64
		formatString: 0
		lineageTag: 37870e2b-72a5-4b74-82f5-d0c3d12b13ec
		summarizeBy: sum
		sourceColumn: acousticness_%

		annotation SummarizationSetBy = Automatic

	column instrumentalness_%
		dataType: int64
		formatString: 0
		lineageTag: 2d4d1dfc-fb93-4d6a-9d52-02d28aff96ff
		summarizeBy: sum
		sourceColumn: instrumentalness_%

		annotation SummarizationSetBy = Automatic

	column liveness_%
		dataType: int64
		formatString: 0
		lineageTag: d66fb691-fd33-401a-a5c8-d9d4b6f4e8b8
		summarizeBy: sum
		sourceColumn: liveness_%

		annotation SummarizationSetBy = Automatic

	column speechiness_%
		dataType: int64
		formatString: 0
		lineageTag: de1f0134-0965-406a-99a8-bc1c911aa652
		summarizeBy: sum
		sourceColumn: speechiness_%

		annotation SummarizationSetBy = Automatic

	column cover_url
		dataType: string
		lineageTag: af5b6b2e-778e-42fd-bdd8-0fa7b859d34a
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: cover_url

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09b2056d-e566-44b4-a323-6fb4debfbd10
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Spotify Dataset' = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents("D:\OneDrive\Desktop\Dashboard Spotify\Spotify Dataset.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Spotify Dataset", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"artist(s)_name", type text}, {"artist_count", Int64.Type}, {"released_year", Int64.Type}, {"released_month", Int64.Type}, {"released_day", Int64.Type}, {"in_spotify_playlists", Int64.Type}, {"in_spotify_charts", Int64.Type}, {"streams", Int64.Type}, {"in_apple_playlists", Int64.Type}, {"in_apple_charts", Int64.Type}, {"in_deezer_playlists", Int64.Type}, {"in_deezer_charts", Int64.Type}, {"in_shazam_charts", Int64.Type}, {"bpm", Int64.Type}, {"key", type text}, {"mode", type text}, {"danceability_%", Int64.Type}, {"valence_%", Int64.Type}, {"energy_%", Int64.Type}, {"acousticness_%", Int64.Type}, {"instrumentalness_%", Int64.Type}, {"liveness_%", Int64.Type}, {"speechiness_%", Int64.Type}, {"cover_url", type text}}, "es"),
				    #"Columna combinada insertada" = Table.AddColumn(#"Tipo de columna cambiado", "Combinada", each Text.Combine({Text.From([released_day], "es-ES"), "/", Text.From([released_month], "es-ES"), "/", Text.From([released_year], "es-ES")}), type text),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna combinada insertada",{{"Combinada", "Date"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Date", type date}})
				in
				  #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

